# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Honza
tagline:          "Guide to the code where dragons lives"
description:      "Guide to the code where dragons lives"
url:              https://honza889.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         8

gems: [jekyll-paginate]

